# Github Action - Basic

name: Github-Basic-Action
on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - uses: actions/checkout@v2
      - run: make lint;
